// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EmployeeTasksManager.Models;

public partial class EmployeeTasksManagerContext : DbContext
{
    public EmployeeTasksManagerContext(DbContextOptions<EmployeeTasksManagerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeTask> EmployeeTasks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07D3EA9B43");

            entity.HasIndex(e => e.NormalizedEmail, "IX_Employees_NormalizedEmail");

            entity.HasIndex(e => e.NormalizedUserName, "IX_Employees_NormalizedUserName");

            entity.HasIndex(e => e.NormalizedEmail, "UQ__Employee__368B291ADC08E94F").IsUnique();

            entity.HasIndex(e => e.NormalizedUserName, "UQ__Employee__54E8BE223433B3D9").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Employee__A9D10534171792B5").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ__Employee__C9F28456032B745A").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NormalizedEmail)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Employee");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(256);
        });

        modelBuilder.Entity<EmployeeTask>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC0771FB8DB9");

            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.DueDate).HasColumnType("datetime");
            entity.Property(e => e.EmployeeId)
                .IsRequired()
                .HasMaxLength(450);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TaskCreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeTasks)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK__EmployeeT__Emplo__5812160E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}